<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pg</string>
	</array>
	<key>name</key>
	<string>WeBWorK PG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.pg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>source.pg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(TEXT|DOCUMENT|ENDDOCUMENT|Real|random|context|uprob|tprob|ucfirst|ans_rule|Context|C|RadioButtons|with|join)(\()</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$|\@)([A-Za-z][A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>variable.other.pg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>( = )</string>
			<key>name</key>
			<string>storage.pg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>end</key>
			<string>(\")</string>
			<key>name</key>
			<string>string.quoted.double.pg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\[A-Za-z]+)</string>
					<key>name</key>
					<string>support.function.pg</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\$|\@)([A-Za-z][A-Za-z0-9_]+)</string>
					<key>name</key>
					<string>variable.other.pg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(BEGIN_TEXT)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.pg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(END_TEXT)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.pg</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.quote.pg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\\)([A-Za-z][A-Za-z0-9_]+)({)([A-Za-z][A-Za-z0-9_]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.pg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.pg</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>source.pg</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.pg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.pg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.pg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>source.pg</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(ans_rule|ucfirst|row|buttons|BeginList|EndList|join)(\()</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\$PAR|\$BR|\$ITEM)</string>
					<key>name</key>
					<string>support.variable.pg</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\$|\@)([A-Za-z][A-Za-z0-9_]+)</string>
					<key>name</key>
					<string>variable.other.pg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(BEGIN_HINT)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.pg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(END_HINT)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.pg</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.quote.pg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\\)([A-Za-z][A-Za-z0-9_]+)({)([A-Za-z][A-Za-z0-9_]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.pg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.pg</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>source.pg</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.pg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.pg</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.pg</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>source.pg</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(ans_rule|ucfirst|row|buttons|BeginList|EndList|join)(\()</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\$PAR|\$BR|\$ITEM)</string>
					<key>name</key>
					<string>support.variable.pg</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\$|\@)([A-Za-z][A-Za-z0-9_]+)</string>
					<key>name</key>
					<string>variable.other.pg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.perl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pg</string>
	<key>uuid</key>
	<string>dc7bd15d-2ecb-4dff-8855-c733b9e6f186</string>
</dict>
</plist>
